# Generated by Django 2.2 on 2019-04-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
