# Generated by Django 2.2 on 2019-04-29 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20190426_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gas_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
    ]
