# Generated by Django 2.2 on 2019-04-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20190423_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
