# Generated by Django 2.2 on 2019-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20190429_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin',
            field=models.CharField(max_length=50),
        ),
    ]
