# Generated by Django 2.2 on 2019-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20190429_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(max_length=42),
        ),
    ]
