# Generated by Django 2.2 on 2019-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
