# Generated by Django 2.2 on 2019-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20190425_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(default=None, max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(default=None, max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin',
            field=models.CharField(default=None, max_length=42),
        ),
    ]
