# Generated by Django 2.2 on 2019-04-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20190425_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.CharField(default=None, max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
    ]
