# Generated by Django 2.2 on 2019-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20190429_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=42),
        ),
    ]
