# Generated by Django 2.2 on 2019-04-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20190426_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin',
            field=models.CharField(max_length=42),
        ),
    ]
